spring:
  datasource:
    url: jdbc:h2:mem:testdb # http://localhost:8080/h2-console ? db server ?? ??
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop # ?????? ? ??? ???? ???
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect